import express from "express";
import { createArticle, deleteArticle, getAllArticlesByTitle, seeAllArticles, seeArticleByAuthor, seeArticleById, seeArticlesByAuthorAndCategory, seeArticlesByCategory, seeArticlesByDate, seeArticlesByKeyword, seeMyArticles, updateArticle } from "../controller/article.controller.js";
import multer from "multer";
import { auth, isAdmin } from "../middleware/auth.js";
const router = express.Router();
const upload = multer({ dest: "public/article" });
router.post("/", auth, isAdmin, upload.array("images"), createArticle);
router.get("/my-articles", auth, isAdmin, seeMyArticles);
router.get("/all", auth, isAdmin, seeAllArticles);
router.get("/:id", auth, isAdmin, seeArticleById);
router.put("/:id", auth, isAdmin, upload.array("images"), updateArticle);
router.delete("/:id", auth, isAdmin, deleteArticle);
router.get("/search", auth, isAdmin, getAllArticlesByTitle);
router.get("/author/:authorId", auth, isAdmin, seeArticleByAuthor);
router.get("/category/:category", auth, isAdmin, seeArticlesByCategory);
router.get("/date", auth, isAdmin, seeArticlesByDate);
router.get("/keyword", auth, isAdmin, seeArticlesByKeyword);
router.get("/author/:authorId/category/:category", auth, isAdmin, seeArticlesByAuthorAndCategory);
export default router;
